/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/risks/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess Risk */
        post: operations["assess_risk_risks_assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Risks */
        get: operations["list_risks_risks_get"];
        put?: never;
        /** Create Risk */
        post: operations["create_risk_risks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orphans/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Orphans */
        post: operations["refresh_orphans_orphans_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_portal_preferences_get"];
        /** Set Preferences */
        put: operations["set_preferences_portal_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/migration/resolve/{legacy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Legacy */
        get: operations["resolve_legacy_migration_resolve__legacy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orphans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orphans */
        get: operations["orphans_orphans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Rollup */
        get: operations["portfolio_rollup_planning_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Docs */
        get: operations["list_docs_docs_get"];
        put?: never;
        /** Write Doc */
        post: operations["write_doc_docs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doc */
        get: operations["get_doc_docs__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{doc_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doc Versions */
        get: operations["get_doc_versions_docs__doc_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_tickets_get"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quarantine */
        get: operations["list_quarantine_tickets_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Transition Ticket */
        patch: operations["transition_ticket_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/tickets/{ticket_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comments */
        get: operations["get_comments_tickets__ticket_id__comments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Community Search */
        get: operations["community_search_community_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attachments */
        get: operations["list_attachments_tickets__ticket_id__attachments_get"];
        put?: never;
        /** Add Attachment */
        post: operations["add_attachment_tickets__ticket_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/encrypt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encrypt Ticket */
        post: operations["encrypt_ticket_tickets__ticket_id__encrypt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/community-visible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote */
        post: operations["promote_tickets__ticket_id__community_visible_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/inbound-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound Email */
        post: operations["inbound_email_tickets_inbound_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Slack Capture */
        post: operations["slack_capture_slack_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/link-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Slack Link */
        post: operations["slack_link_slack_link_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identities/erasures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Erasures */
        get: operations["list_erasures_identities_erasures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identities/{opaque_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Erase Identity */
        delete: operations["erase_identity_identities__opaque_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/migration/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Migration */
        post: operations["run_migration_migration_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentIn */
        AttachmentIn: {
            /** Filename */
            filename: string;
            /** Content */
            content: string;
        };
        /** Body_inbound_email_tickets_inbound_email_post */
        Body_inbound_email_tickets_inbound_email_post: {
            /** Raw */
            raw: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Sender */
            sender?: string | null;
        };
        /** Body_slack_capture_slack_capture_post */
        Body_slack_capture_slack_capture_post: {
            /** Reactor */
            reactor: string;
            /** Author */
            author: string;
            /**
             * Snapshot
             * @default
             */
            snapshot: string;
        };
        /** Body_slack_link_slack_link_ticket_post */
        Body_slack_link_slack_link_ticket_post: {
            /** Reactor */
            reactor: string;
            /** Ticket Id */
            ticket_id: string;
            /**
             * Snapshot
             * @default
             */
            snapshot: string;
        };
        /** Body_write_doc_docs_post */
        Body_write_doc_docs_post: {
            /** Path */
            path: string;
            /** Content */
            content: string;
            /** Base Rev */
            base_rev?: string | null;
        };
        /** DocDetailOut */
        DocDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Space */
            space: string;
            /** Body */
            body: string;
            /** Schema Version */
            schema_version: number;
            /** Path */
            path: string | null;
            /** Rev */
            rev: string | null;
            /** Created */
            created: string | null;
            /** Updated */
            updated: string | null;
        };
        /** DocSummaryOut */
        DocSummaryOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Space */
            space: string;
        };
        /** DocVersionOut */
        DocVersionOut: {
            /** Rev */
            rev: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
            /** Message */
            message: string;
        };
        /** DocWriteOut */
        DocWriteOut: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Space */
            space: string;
            /** Rev */
            rev: string | null;
        };
        /** EpicOut */
        EpicOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Capacity */
            capacity: number;
        };
        /** ErasureReceiptOut */
        ErasureReceiptOut: {
            /** Subject */
            subject: string;
            /** Actor */
            actor: string;
            /** At */
            at: string;
            /** Identity Removed */
            identity_removed: boolean;
            /** Relations Purged */
            relations_purged: number;
            /** Quarantine Purged */
            quarantine_purged: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MigrationRunIn */
        MigrationRunIn: {
            /** Items */
            items: components["schemas"]["SourceItemIn"][];
        };
        /** OrphanReportOut */
        OrphanReportOut: {
            /** Resources */
            resources: {
                [key: string]: string[];
            };
            /** Tickets */
            tickets: {
                [key: string]: string[];
            };
            /** As Of */
            as_of: string | null;
            /** Computed */
            computed: boolean;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Epics */
            epics: components["schemas"]["EpicOut"][];
            /** Epic Count */
            epic_count: number;
            /** Total Capacity */
            total_capacity: number;
            /** Next Cursor */
            next_cursor: number | null;
            /** As Of */
            as_of: string | null;
            /** Never Indexed */
            never_indexed: boolean;
        };
        /** PreferenceIn */
        PreferenceIn: {
            /** Preference */
            preference: string;
        };
        /** QuarantineItemOut */
        QuarantineItemOut: {
            /** Claimed From */
            claimed_from: string;
            /** Subject */
            subject: string;
            /** Reason */
            reason: string | null;
            /** Candidate Ticket */
            candidate_ticket: string | null;
        };
        /** RiskAssessIn */
        RiskAssessIn: {
            /**
             * Category
             * @enum {string}
             */
            category: "delivery" | "security" | "compliance" | "operational" | "strategic";
            /** Likelihood */
            likelihood: number;
            /** Impact */
            impact: number;
        };
        /** RiskCreateIn */
        RiskCreateIn: {
            /**
             * Category
             * @enum {string}
             */
            category: "delivery" | "security" | "compliance" | "operational" | "strategic";
            /** Likelihood */
            likelihood: number;
            /** Impact */
            impact: number;
            /** Title */
            title: string;
            /** Space */
            space: string;
            /**
             * Strategy
             * @default mitigated
             * @enum {string}
             */
            strategy: "resolve" | "owned" | "accepted" | "mitigated";
        };
        /** RiskViewOut */
        RiskViewOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Space */
            space: string;
            /** Category */
            category: string;
            /** Score */
            score: number;
            /** Severity */
            severity: string;
            /** Fires Critical Webhook */
            fires_critical_webhook: boolean;
        };
        /** SourceItemIn */
        SourceItemIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "jira" | "confluence";
            /** Old Id */
            old_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Marked
             * @default false
             */
            marked: boolean;
            /** Reporter */
            reporter?: string | null;
            /**
             * Space
             * @default support/service-desk
             */
            space: string;
        };
        /** TicketCreateIn */
        TicketCreateIn: {
            /**
             * Origin
             * @enum {string}
             */
            origin: "email" | "web" | "slack" | "api";
            /** Requester */
            requester?: string | null;
            /**
             * Encrypt
             * @default false
             */
            encrypt: boolean;
            /** Body */
            body?: string | null;
        };
        /** TicketSummaryOut */
        TicketSummaryOut: {
            /** Id */
            id: string;
            /** Requester */
            requester: string | null;
            /** Status */
            status: string;
            /** Assignee */
            assignee: string | null;
            /** Origin */
            origin: string;
            /** Created At */
            created_at: string | null;
            /** Community Visible */
            community_visible: boolean;
        };
        /** TicketTransitionIn */
        TicketTransitionIn: {
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assess_risk_risks_assess_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskAssessIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_risks_risks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskViewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_risk_risks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_orphans_orphans_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_portal_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_preferences_portal_preferences_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_legacy_migration_resolve__legacy_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                legacy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orphans_orphans_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_rollup_planning_portfolio_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: number;
            };
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_docs_docs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_doc_docs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_write_doc_docs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocWriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doc_docs__doc_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doc_versions_docs__doc_id__versions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_tickets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quarantine_tickets_quarantine_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_ticket_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketTransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comments_tickets__ticket_id__comments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    community_search_community_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attachments_tickets__ticket_id__attachments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_attachment_tickets__ticket_id__attachments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encrypt_ticket_tickets__ticket_id__encrypt_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_tickets__ticket_id__community_visible_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbound_email_tickets_inbound_email_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_inbound_email_tickets_inbound_email_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slack_capture_slack_capture_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_slack_capture_slack_capture_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slack_link_slack_link_ticket_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_slack_link_slack_link_ticket_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_erasures_identities_erasures_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureReceiptOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_identity_identities__opaque_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path: {
                opaque_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_migration_migration_run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-spike-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
